---
title: "Antimicrobial-resistant Enterobacterales in people with HIV: 2021-2023"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    code_folding: show
    toc: yes
    toc_depth: 3
    toc_float: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(warning = FALSE, message = FALSE, error = FALSE, eval = TRUE, tidy = TRUE, cache = FALSE)
```

```{r libraries}
packages <- function(x){
  for(i in x){
     if(!require(i, character.only = TRUE)){
      install.packages(i, dependencies = TRUE)
       library(i, character.only = TRUE)
    }
  }
}
packages(c("readr", "readxl", "haven", "tidyverse" , "data.table" , "naniar", "rockchalk", "lubridate", "kableExtra", "DT", "formatR", "zoo", "binom", "plotly", "janitor", "sjlabelled", "Hmisc", "rms", "aod", "sandwich", "lmtest", "tableone", "broom", "gmodels", "arsenal", "investr", "RColorBrewer", "lessR"))
```

```{r}
culture_data_clean_2014_2021 <- readRDS("Z:/culture_data_clean_2014_2021.rds")
culture_data_clean_2021_2023 <- readRDS("//ad.unc.edu/med/tracs/Groups/Research/CDWH/Van Duin_David_IRB23-2326//entero_isolates_2021_2023.rds")
existing_mrns <- read_excel("//ad.unc.edu/med/tracs/Groups/Research/CDWH/Van Duin_David_IRB23-2326/ExistingDatasetMRNs.xlsx")
```

## **Existing MRNs**

```{r}
mrns <- existing_mrns |>
  clean_names() |>
  mutate_if(is.character, tolower) |>
  dplyr::rename(pat_demrnid = current_pat_demrnid,
                pat_deid = current_pat_deid)
```

```{r}
# Combine datasets 2014-2023
df_2014_21 <- culture_data_clean_2014_2021 |>
  arrange(result_date, pat_mrn_id) |>
  dplyr::rename(original_file_mrn = pat_mrn_id,
                ethnicity_recode = ethnicity) |>
  select(-c(specimen_source, specimen_type, susceptibility, patient_race)) |>
  filter(!str_detect(organism_name, "species|family")) |>
  left_join(mrns) |>
  filter(!is.na(pat_deid))

n_distinct(df_2014_21$isolate_id)
n_distinct(df_2014_21$original_file_mrn)
# 95,358 isolates
# 80,526 patients

df_2021_23 <- culture_data_clean_2021_2023 |> 
  select(-c(parent_hospital, department_name, order_date))

enterobacterales_all <- df_2014_21 |>
  bind_rows(df_2021_23) |>
  select(pat_deid, original_file_mrn, isolate_id, birth_date, death_date, gender, race_recode, ethnicity_recode, zip_code, result_date, culture_year, isolate_source, organism_name, genus, antibiotic, nonsusceptible, antibiotic_class, resistant_to_class, mdr)
```

```{r}
# Remove 10,306 repeat isolates
enterobacterales_all_final <- enterobacterales_all |>
  group_by(pat_deid, organism_name) |>
  slice_min(result_date) |>
  ungroup()

n_distinct(enterobacterales_all_final$isolate_id)
n_distinct(enterobacterales_all_final$pat_deid)
# 159,603 isolates
# 130,289 patients
```

```{r}
enterobacterales_all_final |>
  select(original_file_mrn, pat_deid, isolate_id, culture_year, organism_name, mdr) |>
  distinct() |>
  tabyl(culture_year, mdr) |>
  adorn_totals("row") |>
  adorn_totals("col") |>
  adorn_percentages() |>
  adorn_pct_formatting() |>
  adorn_ns() |>
  adorn_title()

enterobacterales_all_final |>
  select(isolate_id, genus) |>
  distinct() |>
  tabyl(genus) |>
  adorn_pct_formatting()

enterobacterales_all_final |>
  select(isolate_id, isolate_source) |>
  distinct() |>
  tabyl(isolate_source) |>
  adorn_pct_formatting()

enterobacterales_all_final |>
  select(isolate_id, antibiotic_class, resistant_to_class) |>
  distinct() |>
  tabyl(antibiotic_class, resistant_to_class) |>
  adorn_totals("row") |>
  adorn_totals("col") |>
  adorn_percentages() |>
  adorn_pct_formatting() |>
  adorn_ns() |>
  adorn_title()
```

```{r}
# write_rds(enterobacterales_all_final, "//ad.unc.edu/med/tracs/Groups/Research/CDWH/Van Duin_David_IRB23-2326//entero_isolates_2014_2023.rds")
```











